services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trtmc-dev
    working_dir: /workspace/tensorrt-model-connect
    tty: true
    stdin_open: true
    gpus: all
    environment:
      - TRT_ROOT=/opt/trt
    volumes:
      - ./:/workspace/tensorrt-model-connect
      - /home/yifeif/repos/trt/build/tensorrt-base-dev/rel-10.15-native-x86_64-ubuntu20.04-cuda11.8-auto/cmake:/opt/trt:ro
