FROM nvidia/cuda:13.0.0-devel-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    ca-certificates \
    pkg-config \
    python3 \
    python3-venv \
    python3-pip \
    libnvinfer-headers-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/trt-transformers-cpp

CMD ["bash"]
